# Generated by Django 3.1.7 on 2021-04-02 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_slider_link2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='link2',
        ),
        migrations.AddField(
            model_name='slider',
            name='field',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
