# Generated by Django 3.1.7 on 2021-04-02 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='field',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
